//引入第三方库
require('./lib/swiper-3.3.1.min');
require('./lib/spa.min');
require('./lib/iscroll');
//引入自己的库
require('./views/index');
require('./views/home');
require('./views/mine');
require('./views/search');
require('./views/guide');
//设置默认显示试图
SPA.config({
	indexView:"index"
})